# Generated by Django 3.0.7 on 2020-06-24 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Punter')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pun', models.CharField(max_length=400, verbose_name='The Pun')),
                ('timestamp', models.DateTimeField()),
                ('punter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Punter', verbose_name='Punter')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
