# Generated by Django 3.0.7 on 2020-06-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Theme of the Pun Run')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
            options={
                'ordering': ('date_from',),
            },
        )
    ]
