# Generated by Django 3.0.7 on 2020-06-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_run_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pun',
            name='punter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Punter', verbose_name='Punter'),
        ),
    ]
